build_windows:
  stage: build
  script:
    - git submodule sync
    - git submodule update --init --recursive
    - '& $vcpkg integrate install'
    - '& $msbuild -p:Configuration=Release -p:Platform=x64 -r'
  artifacts:
    paths:
      - x64\Release
      - examples\csharp\BleedBlackCSharp\bin\Release
    expire_in: 1 week
  tags:
    - windows
