stages:
  - build
  - sign

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - bleedblack/vcpkg_installed
    - blipcsrv/vcpkg_installed

build_windows:
  stage: build
  artifacts:
    untracked: true
  image: cr.gluon.hu/mihaly/buildtools2019:wdk
  script:
    - nuget.exe restore
    - msbuild -p:Configuration=Release -p:Platform=x64 -r -m
  tags:
    - windows
  variables:
      GIT_SUBMODULE_STRATEGY: recursive

sign:
  stage: sign
  image: cr.gluon.hu/mihaly/osslsigncode:latest
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}_${CI_COMMIT_SHORT_SHA}_${CI_JOB_ID}"
    paths:
      - x64/Release
      - examples/csharp/BleedBlackCSharp/bin/Release
    expire_in: 1 week
  dependencies: 
    - build_windows
  script:
    - |
      curl --output certino.zip --location --header "PRIVATE-TOKEN: $CERTINO_PROJECT_TOKEN" "$CI_API_V4_URL/projects/$CERTINO_PROJECT_ID/jobs/artifacts/main/download?job=package"
      unzip certino.zip -d certino
      osslsigncode sign -ac certino/bundle/ca.cer -certs certino/bundle/cert.crt -key certino/bundle/pvk.key -h sha256 -in x64/Release/bleedblack.sys -out x64/Release/bleedblack_signed.sys
      rm x64/Release/bleedblack.sys
      mv x64/Release/bleedblack_signed.sys x64/Release/bleedblack.sys
  tags:
    - linux
