image: registry.mihaly.me/buildtools2019:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - bleedblack/vcpkg_installed
    - blipcsrv/vcpkg_installed

build_windows:
  stage: build
  script:
    - nuget.exe restore
    - msbuild -p:Configuration=Release -p:Platform=x64 -r -m
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}_${CI_COMMIT_SHORT_SHA}_${CI_JOB_ID}"
    paths:
      - x64\Release
      - examples\csharp\BleedBlackCSharp\bin\Release
    expire_in: 1 week
  tags:
    - windows
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
