name: WDK
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build solution
        run: msbuild ${{ env.Solution_Path }} -p:Configuration=${{ env.Configuration }} -p:Platform=${{ env.Platform }} -r -m
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
          Solution_Path: bleedblack.sln

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.configuration }}-${{ matrix.platform }}
          path: |
            exec/${{ matrix.platform }}_${{ matrix.configuration }}
            managed/bleedblack.net/bin/${{ matrix.configuration }}/netstandard2.0
            examples/csharp/BleedBlackCSharp/bin/${{ matrix.configuration }}
