name: WDK
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build solution
        run: |
          msbuild bleedblack.sln -t:bleedblack,blipcsrv,driver\bleedblack,examples\cpp\BleedblackCpp  -p:Configuration=${{ env.Configuration }} -p:Platform=${{ env.Platform }} -r -m
          msbuild bleedblack.sln -t:managed\bleedblack_net,examples\csharp\BleedblackCSharp  -p:Configuration=${{ env.Configuration }} -p:Platform=${{ env.Platform }} -r -m

        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
